added backened details and s3 bucket and dynamodb for state managemnet

diff --git a/.github/workflows/infrastructure-as-code.yml b/.github/workflows/infrastructure-as-code.yml
--- a/.github/workflows/infrastructure-as-code.yml
+++ b/.github/workflows/infrastructure-as-code.yml
@@ -6,6 +6,9 @@ on:
 env:
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  AWS_DEFAULT_REGION: "eu-west-1" 
+  BUCKET_NAME: "skillpulse-bucket-state"
+  TABLE_NAME: "skillpulse-table-state"
 
 jobs:
   terraform:
@@ -53,7 +56,31 @@ jobs:
             exit 1
           fi
           echo "✅ AWS Credentials verified successfully."
+        
+        # Ensure Terraform Backend Exists
+      - name: terraform backend
+        run: |
+          # Create S3 Bucket if it does not exist
+          if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
+            echo "S3 bucket missing. Creating..."
+            aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$AWS_DEFAULT_REGION"
+            aws s3api put-bucket-versioning --bucket "$BUCKET_NAME" --versioning-configuration Status=Enabled
+          fi
 
+          # Create DynamoDB Table if it does not exist
+          if ! aws dynamodb describe-table --table-name "$TABLE_NAME" 2>/dev/null; then
+            echo "DynamoDB table missing. Creating..."
+            aws dynamodb create-table \
+              --table-name "$TABLE_NAME" \
+              --attribute-definitions AttributeName=LockID,AttributeType=S \
+              --key-schema AttributeName=LockID,KeyType=HASH \
+              --billing-mode PAY_PER_REQUEST
+          
+            echo "Waiting for DynamoDB table to become active..."
+            aws dynamodb wait table-exists --table-name "$TABLE_NAME"
+          fi
+
+        
       # Step 4: Terraform Initialization
       - name: Terraform Init
         env:
